/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonFooter: typeof import('./src/components/CommonFooter.vue')['default']
    CommonHeader: typeof import('./src/components/CommonHeader.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: (typeof import('element-plus/es'))['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox']
    ElCheckboxGroup: (typeof import('element-plus/es'))['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: (typeof import('element-plus/es'))['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: (typeof import('element-plus/es'))['ElForm']
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: (typeof import('element-plus/es'))['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: (typeof import('element-plus/es'))['ElOption']
    ElRadio: (typeof import('element-plus/es'))['ElRadio']
    ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: (typeof import('element-plus/es'))['ElSelect']
    ElSwitch: (typeof import('element-plus/es'))['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: (typeof import('element-plus/es'))['ElTag']
    ElTimePicker: (typeof import('element-plus/es'))['ElTimePicker']
    Header: (typeof import('./src/components/Header.vue'))['default']
    HelloWorld: (typeof import('./src/components/HelloWorld.vue'))['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
